name: Deploy to Heroku
on:
  push:
    branches:
    - release
jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: currencyflip
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        appdir: "backend"
        branch: ${{github.ref_name}}